### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by urbancamo**

### CODE REVIEW

**Comment by mischah** [comment]
Hej @urbancamo it seems, that the »Review required« setting doesn’t make sense since your are the only maintainer for now 😅

Let me know if you can edit the settings by your own over here:
https://github.com/micromata/javaapiforkml/settings/branch_protection_rules/28244031

Otherwise I’ll change the settings for you.

**Comment by mischah** [comment]
P.S. I think your latest email was catched by serverside spam filter. Please send them again. It should pass now (after updating the rules).

**Comment by urbancamo** [comment]
Hi Michael

I get a 404 when attempting to access that page whilst logged in, so I guess I can’t change the setting myself ;)

Regards, Mark.

--
M0NOM/P   ADIF Processor

**Comment by mischah** [comment]
Hej, I’ve changed it for now.

Thought you would be able to do this with the role I gave you:
image

🧐

**Pull request merged**
